### ISSUE TITLE
Add a --help flag

### ISSUE THREAD

**Issue by srevinsaju** [kewbish/zoomy#1]
Thanks for the project. Helps a lot for my "Zoom academy" meetings.
I would be glad to have added a `--help` or `help` or `-h`argument to know more about zoomy
It is not urgent, but it might enhance it.

One more minor issue: 
Is it possible to display the help when no alias is given
When I type
```
zoomy
```
I get no output, nor does anything happen. 
Thanks

**Comment by kewbish** [comment]
This is a great point, I'll work on it soon.

Regarding the `zoomy` bit, you should be getting an error message indicating there are no arguments at the moment. I'll look into why this isn't happening.
